### ISSUE TITLE
Why no ISO style keyboard?

### ISSUE THREAD

**Issue by Supermagnum** [herpiko/unk#4]
Hello, as there are no ISO style keyboards that are split and ergonomic I think that it is a good idea to make that available. It is clearly a marketing opportunity there.
Here is my version of a non-split keyboard in ISO style, with Norwegian QWERTY and Dvorak.
It doesn't have a num pad, but some people may want that.
http://www.keyboard-layout-editor.com/#/gists/53284f72c23040b29def237b7399e567

**Comment by herpiko** [comment]
You only need to modify the plate's SVG file to do this. The rest is very easy/customizable since this is a handwired keyboard.
